[package]
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Ruby parser nodes data"
edition = "2018"
license = "MIT"
name = "lib-ruby-parser-nodes"
repository = "https://github.com/lib-ruby-parser/nodes"
version = "0.21.0"

[dependencies]
