name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi

      - run: cargo build --example codegen --release --target wasm32-wasi

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/wasm32-wasi/release/examples/codegen.wasm
          token: ${{ secrets.GITHUB_TOKEN }}
